#!/usr/bin/env bash
# build.sh
# Render Static Site-এর Build Command হিসেবে এটি সেট করতে হবে:
#   bash build.sh
#
# এই স্ক্রিপ্ট Render-এর Environment Variables থেকে সিক্রেট পড়ে
# config.js ফাইল তৈরি করে (রুট লেভেলে)। ফলে কোনো সিক্রেট
# রিপোজিটরিতে commit হয় না, কিন্তু ডিপ্লয়েড সাইটে পৌঁছে যায়।
#
# Render Dashboard → Environment Variables-এ সেট করতে হবে:
#   FIREBASE_API_KEY, FIREBASE_AUTH_DOMAIN, FIREBASE_PROJECT_ID,
#   FIREBASE_STORAGE_BUCKET, FIREBASE_MESSAGING_SENDER_ID, FIREBASE_APP_ID,
#   IMGBB_API_KEY, WHATSAPP_NUMBER, TELEGRAM_USERNAME

set -e

echo "🔧 config.js তৈরি করা হচ্ছে Render environment variables থেকে..."

# প্রয়োজনীয় env var চেক
required_vars=(
  "FIREBASE_API_KEY"
  "FIREBASE_AUTH_DOMAIN"
  "FIREBASE_PROJECT_ID"
  "FIREBASE_STORAGE_BUCKET"
  "FIREBASE_MESSAGING_SENDER_ID"
  "FIREBASE_APP_ID"
  "IMGBB_API_KEY"
  "WHATSAPP_NUMBER"
  "TELEGRAM_USERNAME"
)

for var in "${required_vars[@]}"; do
  if [ -z "${!var}" ]; then
    echo "❌ Error: Environment variable $var সেট করা নেই!"
    exit 1
  fi
done

# config.js জেনারেট
cat > config.js <<EOF
// config.js — Auto-generated by build.sh during Render deploy.
// এই ফাইলটি .gitignore-এ আছে; এটি commit হবে না।
window.__ENV__ = {
  FIREBASE_API_KEY: "${FIREBASE_API_KEY}",
  FIREBASE_AUTH_DOMAIN: "${FIREBASE_AUTH_DOMAIN}",
  FIREBASE_PROJECT_ID: "${FIREBASE_PROJECT_ID}",
  FIREBASE_STORAGE_BUCKET: "${FIREBASE_STORAGE_BUCKET}",
  FIREBASE_MESSAGING_SENDER_ID: "${FIREBASE_MESSAGING_SENDER_ID}",
  FIREBASE_APP_ID: "${FIREBASE_APP_ID}",
  IMGBB_API_KEY: "${IMGBB_API_KEY}",
  WHATSAPP_NUMBER: "${WHATSAPP_NUMBER}",
  TELEGRAM_USERNAME: "${TELEGRAM_USERNAME}",
};
EOF

echo "✅ config.js সফলভাবে তৈরি হয়েছে।"
echo "📁 ফাইল সাইজ: $(wc -c < config.js) bytes"
